# Air configuration for live reloading during development
# See: https://github.com/air-verse/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Array of commands to run before each build
  pre_cmd = []
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  # Array of commands to run after ^C
  post_cmd = []
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary, can setup environment variables when run your app.
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "docs", ".git", "node_modules"]
  # Watch these directories if you specified.
  include_dir = []
  # Watch these files.
  include_file = []
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = false
  # This log file places in your tmp_dir.
  log = "errors.log"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s"

[log]
  # Show log time
  time = false
  # Only show main log (silences watcher, build, runner)
  main_only = false

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
